export const languageLabels = {
  english: {
    english: "English",
    spanish: "Spanish",
    firstName: "First Name",
    lastName: "Last Name",
    username: "Username",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    termsAndConditions: "I accept the terms and conditions",
    nextButton: "Next",
    submitButton: "Submit",
    errorMessages: {
      firstNameRequired: "First name is required",
      firstNamePattern: "Alphabetical characters only",
      firstNameLength:
        "Name must be greater than 2 characters and less than 25",
      lastNameRequired: "Last name is required",
      lastNamePattern: "Alphabetical characters only",
      lastNameLength: "Name must be greater than 2 characters and less than 25",
      usernameRequired: "Username is required",
      usernameMaxLength: "Username should be less than 20 characters",
      emailRequired: "Email is required",
      emailPattern: "Please write correct email address",
      passwordRequired: "Password is required",
      passwordMinLength: "Your password must be greater than 8 characters",
      passwordStrength: "Your password isn't strong enough",
      confirmPasswordRequired: "Please confirm your password",
      confirmPasswordValidate: "Passwords do not match",
      termsAndConditionsRequired: "Please accept the terms and conditions",
    },
  },
  spanish: {
    english: "Inglés",
    spanish: "Español",
    firstName: "Nombre",
    lastName: "Apellido",
    username: "Nombre de usuario",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    termsAndConditions: "Acepto los términos y condiciones",
    nextButton: "Siguiente",
    submitButton: "Enviar",
    errorMessages: {
      firstNameRequired: "Nombre es obligatorio",
      firstNamePattern: "Solo caracteres alfabéticos",
      firstNameLength: "El nombre debe tener más de 2 caracteres y menos de 25",
      lastNameRequired: "Apellido es obligatorio",
      lastNamePattern: "Solo caracteres alfabéticos",
      lastNameLength:
        "El apellido debe tener más de 2 caracteres y menos de 25",
      usernameRequired: "Nombre de usuario es obligatorio",
      usernameMaxLength:
        "El nombre de usuario debe tener menos de 20 caracteres",
      emailRequired: "Correo electrónico es obligatorio",
      emailPattern:
        "Por favor, escriba una dirección de correo electrónico válida",
      passwordRequired: "Contraseña es obligatoria",
      passwordMinLength: "Su contraseña debe tener más de 8 caracteres",
      passwordStrength: "Tu contraseña no es suficientemente segura",
      confirmPasswordRequired: "Por favor, confirme su contraseña",
      confirmPasswordValidate: "Las contraseñas no coinciden",
      termsAndConditionsRequired:
        "Por favor, acepte los términos y condiciones",
    },
  },
};
